apiVersion: v1
kind: Service
metadata:
  labels:
    chart: jenkins-0.1.14
    component: intent-cricket-jenkins-master
    heritage: Tiller
    release: intent-cricket
  name: jenkins
  namespace: jenkins
spec:
  externalIPs:
    - 172.22.84.238
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    component: intent-cricket-jenkins-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
