apiVersion: v1
kind: Service
metadata:
  labels:
    chart: jenkins-0.1.14
    component: intent-cricket-jenkins-master
    heritage: Tiller
    release: intent-cricket
  name: intent-cricket-jenkins
  namespace: jenkins
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: slavelistener
      port: 50000
      protocol: TCP
      targetPort: 50000
  selector:
    component: intent-cricket-jenkins-master
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
