apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "original-request": {
          "url": "/k8s/v1.16/net.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxOSIsIEdpdFZlcnNpb246InYxLjE5LjIiLCBHaXRDb21taXQ6ImY1NzQzMDkzZmQxYzY2M2NiMGNiYzg5NzQ4ZjczMDY2MjM0NWQ0NGQiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDIwLTA5LTE2VDEzOjQxOjAyWiIsIEdvVmVyc2lvbjoiZ28xLjE1IiwgQ29tcGlsZXI6ImdjIiwgUGxhdGZvcm06ImxpbnV4L2FtZDY0In0KU2VydmVyIFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxOSIsIEdpdFZlcnNpb246InYxLjE5LjIiLCBHaXRDb21taXQ6ImY1NzQzMDkzZmQxYzY2M2NiMGNiYzg5NzQ4ZjczMDY2MjM0NWQ0NGQiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDIwLTA5LTE2VDEzOjMyOjU4WiIsIEdvVmVyc2lvbjoiZ28xLjE1IiwgQ29tcGlsZXI6ImdjIiwgUGxhdGZvcm06ImxpbnV4L2FtZDY0In0K",
          "date": "Fri Sep 18 2020 13:03:41 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
  labels:
    name: weave-net
  name: weave-net
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - weave-net
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
