apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:rules: {}
      manager: kubeadm
      operation: Update
      time: "2020-09-17T13:54:33Z"
  name: kubeadm:kubelet-config-1.19
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - kubelet-config-1.19
    resources:
      - configmaps
    verbs:
      - get
