apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXdOakU1TVRZek5sb1hEVEk1TURNd016RTVNVFl6Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWhxClhaRjhIcmhrOGN6T3FuTnp3bjQ0ZEpYUFFrSGR4RitGUENuL0lPeW9lMXdkUE1aWURTZkpyNjlOKzd6MjgwcFYKVWpYdWs2RmpNdlY2U3RnNkMxVlNCZjFSVW0vL0toVWVCSXFPRGFGKzBOQTE4Z1FBRG51UEpsdmlQQm1qbC9YWApCS3k0bmxJTkdseFMwWHdNbldQNE1EYU9HamFRN0xUZUhONDdENlh5aDlYQVZxL1F4SlJIWklpZFU4QkVFRnQ2Ck12U1ZBYU9manhsMjRSVm5VYjBnajVRcFFTWFZzcmNKcWR5QlB4NERtOVV6QkJuWDMxZ0thSGdla2xudWNMSkYKRXVBZnFnOVFLNmJpTXUrbE5Gb1RPc2s3UXRDcU1aN3NPNDZrNkNPd1RBeU9nM3VJTzkyN1pyaVVyR0FTMEJVTgpaQzhGZUF0dGR0NkFrdi9Sd3Q4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMTmRVNTVldlpoalptUzhTWWxmWTJRWVpHSmEKZHVocXNHcUY4UVc0S2l0UzdiZjVqdmtFNWhzL0YyOVV2SlFnaXRVa0hDWGxrYWVoYVZwcndkQ1BxZCtZNURZbgowR1JmQml2TGZwR1hyQ20yZlZXOGU5cDRIaDJYaFBMY0FXN2IzVnJxSWFJNHkrMlZzMCsrVmxvU2pPSkdrWmtSCndPVVhSaUZDb3JLUGZ3clZHbzFkMGZuYUs0aE41cVFydHI1cEZpVlFUYkw1MDNWOUpxbGpQUmdvNDN2TVlwM1gKcXVVMlJsaGh4djNPWTdsb2QzSWo2NGFhZFB6d0lZdzIyUHVNaFV1TUFhcnNvTEJPR1pLMllOK1A1NCtobW5oawpuZy9UNEFibE9uRUIvYllyd1lDRlJOV3gxazVjckthcWF3WDdMdDE2RDBMVjVGcFhsa3FSUThWK3hkYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://172.22.84.238:6443
      name: ""
    contexts: []
    current-context: ""
    kind: Config
    preferences: {}
    users: []
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-public
