apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-gpg-public-keys
  namespace: fluxcd
data:
  flux.asc: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQENBF9lehoBCACVFh3ii7iZmQPNTD2A4ZZZY3+6018yNY1ez7YApWRbLzthWgi8
    HCvoYNpz0uZfG5ur4M3hx7Ygv9yc3w2D841dTeZWKmkpPS1kCt5YrUMWEMm/IU1C
    w/8jsgbb5Jf9mAZLRVVTT9M3M0hBSGHWHqbRVEsAUuofHfxkunTAMjVmslP1za2D
    5xh3/s9u+25Th1s0PRrqKKqOCiIlS1Nr5JajPaHQrvamHiMpfFnhfd52CaYimla8
    MJcz4lrOvorbr95fjZe5EZRQWNAgQ/JFeD+SvdQYLoq1UMDEBaC5mvNtY3AuhGbu
    f9EbnMkZMpguCZX44h4Ap8XJ+e7ourdF/hM5ABEBAAG0J0ZsdXggQXV0b21hdGlv
    biA8a2luZ2RvbkB0ZWFtaGVwaHkuY29tPokBTgQTAQgAOBYhBGY0aH/O3YshUxOC
    eQCyi2VLZCe3BQJfZXoaAhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEACy
    i2VLZCe3g8MH/1ckjPrwTn0est315gbQWvKt6PtCFR1dLehKYGG23fjSPw5fWlLd
    4a0djE68AxBhHtIRn4YgvAS8f2Z0Ss8VNjcu+oPc0DDaJ/rMxvb+w1DZNB74dpX4
    iCbY1KraVBAf3iJ5LmTIPCN9joCOcaFkLy0iH45XuIRV+7I/RZJcmagQ1lNwsaOd
    oXXHwlDVmBPBqZC5sUEUY4xIfv03QQ0Gn69OVPB0C6kMyHMNKazUkl6kFT9zr6Zl
    hUF2l6dUqLIX0BjL6PkwVxzqXeOOOHlESprP424oBWwvfK6nV/Zzwrwu8VsnP2Ca
    ni7HWugp4cbdpOIQvoVEGNMAT3UNF5HcKpy5AQ0EX2V6GgEIAOE+Jo51HF3y/D7G
    GfRqRTms6d8pHadcP8v821K3fOfVn5HkxAVukwHvikuHxioKsPTVB3igSkTlPtGo
    DuD8MYXheC1JmS+qwKW6V3WTsij+0rDVyiIOI1ZtIG7bAr+gXHH24VdT2sT8OOhb
    M4yxBYUxvTP0bFseDnR5B56Zzn72w83J1OqJFeTW7FPqCom9e810NzwaLeP9414e
    j+9ZfdHNd7Ya5pgLUI6hXPSKyfEZRtR9L+YtlSVPSfihtfYTV8CIoCi8vAFZ/rgc
    HjX8RT9QhJ9r8zhJbrqWGYz8w2GAIWTLxo9ZnDk8gxENd0iClgv5ohpO9uSizBet
    t1JrCP0AEQEAAYkBNgQYAQgAIBYhBGY0aH/O3YshUxOCeQCyi2VLZCe3BQJfZXoa
    AhsMAAoJEACyi2VLZCe3tpAH/2cUjXVQVeeB6k5dAbY0KmhwaPxKFD2A7AT23O25
    BJtL5LBVk4jD3K+Fz00YH9hTkQVZ/65NeYR7JLvGo1bcVgmzm5/KYmmQlCGtqVeb
    csmwF2dzF5g4+nlt3WWU209gvD4JQED+kLe6onxJHLVdsPVpNNkLtlchcK1BfS9A
    /iZxhuPNPypqpsG5xc7ZrFvgGsgOl7Y8HVyld9/7VI6BudCocVF2v1BxSZoLgJZj
    s9JwRIxe8oDD0YIFS5/HRAGkDNJzFmD+hMYqtV82HPOcCF859Nsgbb8ewkJcypyu
    Yi9XW0i/8v6QxmEIW1kWpp612acQu+Ia8xQo4/qh0QIEb4M=
    =XRhP
    -----END PGP PUBLIC KEY BLOCK-----
  kingdon.asc: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQENBF9lee8BCACp5Bx/+P3CiiA1jR/yiwqoU4nHZR/djXejksJQ9hozkKnCsRjU
    go991YP9TPPm5hMYMEeUxmcZYtwgkjuY5zM6lGq/ubU8pdGJJYE5RGO+czZ2f00Y
    l7FiHu1dPd0MF1Q8Y1YhGqmFA2hp/ziEu7M77Z1nJ9hJz4EHclDCvkkQGvZZklLm
    Rhpc2vfXcOD6EVpoKwNi6i73VtT4B9jz0c+sZ0nu+hmKiBtl9igZnqIMGCVFMlUK
    0RAurHvem/sjPfeFf08A7k0gsfFsiR6xhAbUNYkyY9uH1xncDAVhFFzu8cuv6guo
    dchezpYVNDhOdOvjPZCyCPJsp/39G/OXvqvZABEBAAG0J0tpbmdkb24gQmFycmV0
    dCA8a2luZ2RvbkB0ZWFtaGVwaHkuY29tPokBTgQTAQgAOBYhBOFvvXdU0ktAXTdK
    KGqgTg1y9C9HBQJfZXnvAhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEGqg
    Tg1y9C9HMZgH/jBRGmAAD51aBf6MIvNTwmlgRJgvzaJCv4mR4xuskbdJeKRg54cN
    9VvexZwra7wIOVZA/kiybNI+q5lL5yxu8gwKmpAslWsBM4R+2b7QGw7v+zMVzoar
    Udkhw06RA/BrM9q9lKdZOxw74eMF+I4AI8r8gtPLGubrtJ4KnaJYc68VBbaOyK0I
    EfdevTVk69mDhnt9657UVEJtWj9Ii59GwCt9iczVo203gLk0DLrRw4jT4stfx9Px
    MB9OLZOlxldEe44ZcC9D5jVGBA+YLl7Vegl0tcs3qZJrc+BgFSztBM1pvmgUKd56
    F3hPe8Z0XxZA0KA2yK54fDqOrFPEpc7htNu5AQ0EX2V57wEIAN/eD1I6QFRg5x36
    FtYrLc4MXv2yC8jLEQckG/XG36dHRlV8OctIxKsfQBTtA5CL0Amtddz8lJt4YdSt
    A3+J9gZ0ga8pP8VGHE0gowm1RgFSecZO6bf2CsX+EWfI/59G7+y1+cQt7HwPyT5s
    WBwnnJxR/5Mqh4/73hTKcYMbs01U3Oo2ea80D/OSe6wW6gS+fRxSGYnDGijQVpOW
    J6whkV8PPZ9YeudcDp4BVrGHggCQd+ZkpwV+bPdoog3bwGx7yWnGTrx5v/oQ5Ejj
    BnUzzVJg4YeWOhfuKhjXvr1OTFw4Kpz8f1EW8DE6DOjSb12jknFbgQ4rx59xgHBE
    5pNJi/cAEQEAAYkBNgQYAQgAIBYhBOFvvXdU0ktAXTdKKGqgTg1y9C9HBQJfZXnv
    AhsMAAoJEGqgTg1y9C9Hd5MH/1EElZ1l2BgCgTS9r+H33U0XHK1/4qIV3a15LVCL
    Vm/vVxf0TB89zNp0bJmYLjBVTVGDgLM/ziLhQhY5CR4gTPGOQQfhLKwoQ0zrQvpg
    pzKXkimCQg+cMNUvDSn6Jx+dp47cC6zxL8011+2zxmdQRHp7eLKmLwTpnhs/R26T
    w7fm4XRKJBwl9d8UR2pnJcppJlCOzjNli/eCRSwLd9YEnLADFrHhS2yfs87xRWmD
    fDl+lnE6HKX/faYklzoIVUjWQqorcg2lUzJSbDGgxwkkH5Yw0NV22C43liPmoybM
    DbPKzRXf76g2DhW9SEe1phUqgtI8GjwXyAY9dlqbb6YwMss=
    =Rpi2
    -----END PGP PUBLIC KEY BLOCK-----
