apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-gpg-public-keys
  namespace: fluxcd
data:
  kingdonb.asc: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQGNBF9UTCgBDADQ14LPn9jV4sOP08ja3un9bF/nM+HPgcOGVYLdQVpTrzPIlnV9
    v+ZeSQew4PGFOS+FqGQuQwvg6H0JOIOw0vtEay2I+Byl0hgTi4DkeY8CjHAwfBi7
    pLU1goYB7fM55gblJ4/4sbP2E2pktTllkYxof7Aj6uv+v7RIO0c1pWqjJTK7t5AB
    D5cNcMPA/GQ8nfN1UhQTG8Ve+NSIL/uIPcYtP4VfTpRYMUzLofH8Fg3QAyMZGtuL
    LxGi9ywMq7Rj2qg88ZWkirE7jdjVBDfa1kY4+FWpxtm4uFaoeb/Mmuwebw7iteE5
    DEqbyYxdIh2yETUYytTr0cSczGkbC+bomWnEt1XZ6UShwRmsc3s8d4Tv++p3LHh4
    bH3SUYmoLeYE4LbxGT/BL7MAOX3sVOTHebOxr3TKcu2uLMh5T7bIXY4HJ7FagsrT
    0jnk+Q4v2Ruq9ENGM32Iqkr+BVLjnTe3t3E+9ppT046mU4Wyd4zElD7d+OZpRjgX
    /XY4Uy2WqFERjJ0AEQEAAbQiS2luZ2RvbiBCYXJyZXR0IDxraW5nZG9uLmJAbmQu
    ZWR1PokB1AQTAQgAPhYhBKgrECUIg2pd81cR9SFzlkv067TSBQJfVEwoAhsDBQkD
    wmcABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJECFzlkv067TSEkML+QGUW+vj
    vXCGiYJ9IAXhIw6XUfP6DSRlQogOevKdY50//UzJ+itOqu8Tp4biztf/489g4U2/
    LmIynEsm6XlY97px4M3uI6eyh/JaL/rBDhufjeJdjxV7f2Y7HDPzhRry4Y85BYr1
    SopdmaY2kLcRsQ9Eh7uQ7CsNYFAZ82Q1M2LSZT0ghY2jmAaVzvd1UooPUo5L23l2
    NknwMrqqHkR4eERLpCpNSN93u3Jceui+zitFn/y0XVNSlLmTvoYI9EcGpMiRxn60
    6j915i5BvNGdBMfGkXIXBu+EHXLtlVRfDAp0zJOwY8457xlpQjID16Wfzn28H2nj
    NiyEDXKzs1AfMRN4X5fgkIbeLy08k9wvGFeCAUuPD01kAvYq1hW+pZrtQCcoPKYV
    VQ7LDsBfXH+4O47fI+JQ6Pmx0xypEtPu1o/ZyUbGFd7oTaSZFqM0gRNrKEXRU7oy
    8m9/sEy/uJyPBnjPvi3n/PUGfssMF4UXK3qZAxDrAnNCTG/pqR2AGZlOJ7kBjQRf
    VEwoAQwA3+Y6w8Ab8/CKKTM21y/zYzJulKQp0gAL+T1U9/HNSDOZgrm2T5FxixkK
    7F5G2S5N/NgrKO1ESfDD7mCKCLxrqh6XYaJ00051kO4bMDvBfPIHrqKFj89IYB7B
    sqqstz+ZeYQewcUnkbLVkSg6Q8io2fNbhhKaCnUjxqSEEXjLQELIvt6alNWlKyrc
    7o0kusCCfk6ZV5svJDd9tI51gvSLq4AgjNhtbxX8ZiE5ai5JzyGyUiBXdUMlFHe8
    mKAXniGS3ZHcu3ItuWd3dSGE2q/8Bq4kdAc8YcstbVpZ0hLQ5X1xsi9rewyVhyyn
    zSmVd9r5XBLnBCjK4mf9cxbhg2vN1CFcXqg0tPoN7Hq6cR+NRjGHDBTkFxxFsDG+
    OX8sR1BGbO98+I+XO3PHnFFBXR4VOMQ82jHuP1zVUjgq7D0qL27TeBYrxYU5rmMZ
    28eLgQrsga+nGL+1NbOvPu93tJ8qRrgDyDBGnVahPyT11jFPWbb8zBbnycVoaEY2
    SPjsAVhlABEBAAGJAbwEGAEIACYWIQSoKxAlCINqXfNXEfUhc5ZL9Ou00gUCX1RM
    KAIbDAUJA8JnAAAKCRAhc5ZL9Ou00sbwC/9cEYoYGI6QGtSQEefvZEpZh9WabbwA
    Zq0xUWZfXyXtFYKyQK3P8lSLhAi1v35Y93c1/mqvVIYzKkJ+ZLYO1zQsixzmk90c
    kpQ56hT2ED61VgWCenn+D5zION3DYr2npip+ixWsne5VxXVMaGo0tFjqXcTH2Vbf
    PhPxW+f0CpDP9aqvdQ2Fc7Q63Yymz7PQwUhx6ZGgvP2rxvE0hUh9eD0t086cm/6E
    11CPytihR05Wh8iudk1vANGj5h0eMKj9Q0bKUs77HMwk1aEms0qolXC0QsDoHq4W
    S5DQRS1lNrg3Sj/oZbJeSpUiwNzdo5VVPAKAGCejT7AFTVOVEFxtrdoBILv94gOo
    Wu3fU2+skeL9FfyyS3PRhaS9WO2F2HONdnjtZb//+0qIj/StpLTDqnuIhjCalNpX
    ePeiLbX1MXhTb01BNKe1uxcl+LNfSzldiqdwLpPHHiQuXs5Et5xqHo5qOMb/yw4B
    1Bohv6nNZGyN3DpqkDeiJfE+j4fKfiD/hsM=
    =pHo4
    -----END PGP PUBLIC KEY BLOCK-----
