apiVersion: v1
kind: PersistentVolume
metadata:
  annotations: {}
  finalizers:
    - kubernetes.io/pv-protection
  name: jenkins-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: intent-cricket-jenkins
    namespace: jenkins
  hostPath:
    path: /data/jenkins/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
