apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXdOakU1TVRZek5sb1hEVEk1TURNd016RTVNVFl6Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWhxClhaRjhIcmhrOGN6T3FuTnp3bjQ0ZEpYUFFrSGR4RitGUENuL0lPeW9lMXdkUE1aWURTZkpyNjlOKzd6MjgwcFYKVWpYdWs2RmpNdlY2U3RnNkMxVlNCZjFSVW0vL0toVWVCSXFPRGFGKzBOQTE4Z1FBRG51UEpsdmlQQm1qbC9YWApCS3k0bmxJTkdseFMwWHdNbldQNE1EYU9HamFRN0xUZUhONDdENlh5aDlYQVZxL1F4SlJIWklpZFU4QkVFRnQ2Ck12U1ZBYU9manhsMjRSVm5VYjBnajVRcFFTWFZzcmNKcWR5QlB4NERtOVV6QkJuWDMxZ0thSGdla2xudWNMSkYKRXVBZnFnOVFLNmJpTXUrbE5Gb1RPc2s3UXRDcU1aN3NPNDZrNkNPd1RBeU9nM3VJTzkyN1pyaVVyR0FTMEJVTgpaQzhGZUF0dGR0NkFrdi9Sd3Q4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMTmRVNTVldlpoalptUzhTWWxmWTJRWVpHSmEKZHVocXNHcUY4UVc0S2l0UzdiZjVqdmtFNWhzL0YyOVV2SlFnaXRVa0hDWGxrYWVoYVZwcndkQ1BxZCtZNURZbgowR1JmQml2TGZwR1hyQ20yZlZXOGU5cDRIaDJYaFBMY0FXN2IzVnJxSWFJNHkrMlZzMCsrVmxvU2pPSkdrWmtSCndPVVhSaUZDb3JLUGZ3clZHbzFkMGZuYUs0aE41cVFydHI1cEZpVlFUYkw1MDNWOUpxbGpQUmdvNDN2TVlwM1gKcXVVMlJsaGh4djNPWTdsb2QzSWo2NGFhZFB6d0lZdzIyUHVNaFV1TUFhcnNvTEJPR1pLMllOK1A1NCtobW5oawpuZy9UNEFibE9uRUIvYllyd1lDRlJOV3gxazVjckthcWF3WDdMdDE2RDBMVjVGcFhsa3FSUThWK3hkYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  namespace: a3ViZS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqVjBaMUYxVFhVek1uSTVablY0TmtGa1VucFZiM1UxZEhreVNFUXpWRTFrTkMxVFdITXRUbVY0Y0RRaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKbGJtUndiMmx1ZEhOc2FXTmxMV052Ym5SeWIyeHNaWEl0ZEc5clpXNHROMjA0WjJjaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNXVZVzFsSWpvaVpXNWtjRzlwYm5SemJHbGpaUzFqYjI1MGNtOXNiR1Z5SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pWW1FMU1tTTRORE10WkdVM05TMDBPVGxqTFRreE1EWXROV1V5WVdRelpUUTVaVEExSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tdDFZbVV0YzNsemRHVnRPbVZ1WkhCdmFXNTBjMnhwWTJVdFkyOXVkSEp2Ykd4bGNpSjkuR01nQk1LV083Y1BoX3FUQTZha09VRDU3RFNBVUhyNFpXQ3dRY1loR3pPV2lJbjFWdWhmamtTMGZMVXI2clRCdDhXaUREb24yXzVuNE9KZmw2QW1sRDlENkhpRExsbnlnUW42THNXVEZOdHNSNDlidl92Q1dGc0hlN3BMWVpuMlhuamE3aktuMEZNWXdTR0pCQmdzZklYX3ltTzYtaUJEVkZaelhxQWNKVnJPOFZadzhUUTVpWHNYUnJlLUxBVzdpMHZyMHV2bkpFUjQySDFLWlRsTkQ3Z2tpVW9Sd3lxSDFyWUpIemdWd2UtcDBkOHBsZk4yWGV3eXZDNGFkbUNKZWlOcGpEVXRZaU1kSjI0aFZnTWdjQVdOWVJzQUxES3cwMzBWSG90UGk0czdCQkhuZXpzX2pGSzIxT3lZZVVmODJWaURxMXpjbU9QV3NoMUtGN09UWnJ3
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: endpointslice-controller
    kubernetes.io/service-account.uid: ba52c843-de75-499c-9106-5e2ad3e49e05
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
          f:namespace: {}
          f:token: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/service-account.name: {}
            f:kubernetes.io/service-account.uid: {}
        f:type: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-04-18T03:07:58Z"
  name: endpointslice-controller-token-7m8gg
  namespace: kube-system
type: kubernetes.io/service-account-token
