apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXdOakU1TVRZek5sb1hEVEk1TURNd016RTVNVFl6Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWhxClhaRjhIcmhrOGN6T3FuTnp3bjQ0ZEpYUFFrSGR4RitGUENuL0lPeW9lMXdkUE1aWURTZkpyNjlOKzd6MjgwcFYKVWpYdWs2RmpNdlY2U3RnNkMxVlNCZjFSVW0vL0toVWVCSXFPRGFGKzBOQTE4Z1FBRG51UEpsdmlQQm1qbC9YWApCS3k0bmxJTkdseFMwWHdNbldQNE1EYU9HamFRN0xUZUhONDdENlh5aDlYQVZxL1F4SlJIWklpZFU4QkVFRnQ2Ck12U1ZBYU9manhsMjRSVm5VYjBnajVRcFFTWFZzcmNKcWR5QlB4NERtOVV6QkJuWDMxZ0thSGdla2xudWNMSkYKRXVBZnFnOVFLNmJpTXUrbE5Gb1RPc2s3UXRDcU1aN3NPNDZrNkNPd1RBeU9nM3VJTzkyN1pyaVVyR0FTMEJVTgpaQzhGZUF0dGR0NkFrdi9Sd3Q4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMTmRVNTVldlpoalptUzhTWWxmWTJRWVpHSmEKZHVocXNHcUY4UVc0S2l0UzdiZjVqdmtFNWhzL0YyOVV2SlFnaXRVa0hDWGxrYWVoYVZwcndkQ1BxZCtZNURZbgowR1JmQml2TGZwR1hyQ20yZlZXOGU5cDRIaDJYaFBMY0FXN2IzVnJxSWFJNHkrMlZzMCsrVmxvU2pPSkdrWmtSCndPVVhSaUZDb3JLUGZ3clZHbzFkMGZuYUs0aE41cVFydHI1cEZpVlFUYkw1MDNWOUpxbGpQUmdvNDN2TVlwM1gKcXVVMlJsaGh4djNPWTdsb2QzSWo2NGFhZFB6d0lZdzIyUHVNaFV1TUFhcnNvTEJPR1pLMllOK1A1NCtobW5oawpuZy9UNEFibE9uRUIvYllyd1lDRlJOV3gxazVjckthcWF3WDdMdDE2RDBMVjVGcFhsa3FSUThWK3hkYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  namespace: a3ViZS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqVjBaMUYxVFhVek1uSTVablY0TmtGa1VucFZiM1UxZEhreVNFUXpWRTFrTkMxVFdITXRUbVY0Y0RRaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKbGJtUndiMmx1ZEhOc2FXTmxiV2x5Y205eWFXNW5MV052Ym5SeWIyeHNaWEl0ZEc5clpXNHRORGhvYm13aUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNXVZVzFsSWpvaVpXNWtjRzlwYm5SemJHbGpaVzFwY25KdmNtbHVaeTFqYjI1MGNtOXNiR1Z5SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pWkRJMk9HUmhZbUV0WlRnNU15MDBOV0pqTFdGaVpqSXRNR1UwTldaa1pEZzVNREZpSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tdDFZbVV0YzNsemRHVnRPbVZ1WkhCdmFXNTBjMnhwWTJWdGFYSnliM0pwYm1jdFkyOXVkSEp2Ykd4bGNpSjkuTlE3SkFRcnhMSXJVdlA5WGpSamMtdzBTYVIwM3Y0WDhlOHZjWU40QzhWeFZOZVZ0dUJlanVESDkxVUZRVDZfZnBIUkhNR21DcG15YkNtclhCTklDNmd1QXNSb0ZkUGJmUFgtY3dmNW4wNWNSMHl4RlMwdkVKT3F6VGUxc2tPSkwtQ0FMbnVhZlJQNUZsNS1uLWNIRkhqSTVpWjZxbmQ4ZWQtZXVTamItZHp3RURUcTF6Qm1EOUlaQ042eDZ2clNFNVFaYURrT1dHR1p6R2duRmVNYUFkY0gtdjhHQTQ4cC1FX256cWJSY2M2OXhXMlA2T3VmXzNKQU9SdmdRWUhIeTc4eURSTVczTlJwM0VHNEVjUWxRLXUzZ1k2R2lLYkdmNTdfNTN4LXQ0R3dMTEFZT0ItbFJveG83a2IwajVXT2Rjck81S1JTZ0ptOEtySVg3Slk4QUh3
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: endpointslicemirroring-controller
    kubernetes.io/service-account.uid: d268daba-e893-45bc-abf2-0e45fdd8901b
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
          f:namespace: {}
          f:token: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/service-account.name: {}
            f:kubernetes.io/service-account.uid: {}
        f:type: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-09-17T13:54:51Z"
  name: endpointslicemirroring-controller-token-48hnl
  namespace: kube-system
type: kubernetes.io/service-account-token
