apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  generation: 193
  labels:
    chart: jenkins-0.1.14
    component: intent-cricket-jenkins-master
    heritage: Tiller
    release: intent-cricket
  name: intent-cricket-jenkins
  namespace: jenkins
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 0
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      component: intent-cricket-jenkins-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        chart: jenkins-0.1.14
        component: intent-cricket-jenkins-master
        heritage: Tiller
        release: intent-cricket
    spec:
      containers:
        - args:
            - --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
            - --argumentsRealm.roles.$(ADMIN_USER)=admin
          env:
            - name: JAVA_OPTS
              value: -Dhudson.model.DirectoryBrowserSupport.CSP=''
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: intent-cricket-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: intent-cricket-jenkins
          image: yebyen/jenkins-master:v0.8.0
          imagePullPolicy: Always
          name: intent-cricket-jenkins
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 50000
              name: slavelistener
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - mountPath: /var/jenkins_config
              name: jenkins-config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: intent-cricket-jenkins
          name: jenkins-config
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: intent-cricket-jenkins
status: {}
