---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  chart:
    repository: https://charts.jenkins.io
    name: jenkins
    version: 3.1.2
  values:
    controller:
      jenkinsUrl: https://jenkins.teamhephy.info
      JCasC:
        securityRealm: |-
          local:
            allowsSignup: false
      ingress:
        enabled: "true"
        paths: []
        apiVersion: "networking.k8s.io/v1"
        hostName: "jenkins.teamhephy.info"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx
        hostName:
        tls:
        - secretName: tls-jenkins
          hosts:
            - jenkins.teamhephy.info
      persistence:
        enabled: "true"
      initializeOnce: "true"
