---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  chart:
    repository: https://charts.jenkins.io
    name: jenkins
    version: 2.6.4
  values:
    master:
      ingress:
        enabled: "true"
        apiVersion: "networking.k8s.io/v1"
        hostName: "jenkins.teamhephy.info"
      persistence:
        enabled: "true"
      initializeOnce: "true"
