---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/ignore: "true"
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.1.0
  values:
    controller:
      kind: DaemonSet
      config:
        hsts: "false"
      hostNetwork: "true"
      daemonset:
        useHostPort: "true"
      service:
        type: NodePort
