apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: intent-cricket-jenkins
    chart: jenkins-0.1.14
    heritage: Tiller
    release: intent-cricket
  name: intent-cricket-jenkins
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  volumeName: jenkins-data
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
